[tool.black]
line-length = 100
target-version = ['py310']
skip-string-normalization = true
exclude = '''
/(
    | .git
    | .mypy_cache
    | .pytest_cache
    | .exclude
    | .venv
    | __pycache__
    | .env
    | migrations
)/
'''
